spring:
  config:
    activate:
      on-profile: prod

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    com.eusun97.stocktracker: INFO