-- 종목 마스터
CREATE TABLE stock (
    ticker      VARCHAR(10)  PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    market      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT now()
);

-- 거래내역 (append-only + soft delete)
CREATE TABLE trade (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker      VARCHAR(10)    NOT NULL REFERENCES stock(ticker),
    tx_type     VARCHAR(10)    NOT NULL,
    quantity    NUMERIC(19, 4) NOT NULL,
    price       NUMERIC(19, 4) NOT NULL,
    traded_at   DATE           NOT NULL,
    created_at  TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP      NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMP      NULL,
    CONSTRAINT chk_trade_tx_type  CHECK (tx_type IN ('BUY', 'SELL')),
    CONSTRAINT chk_trade_quantity CHECK (quantity > 0),
    CONSTRAINT chk_trade_price    CHECK (price >= 0)
);

CREATE INDEX idx_trade_ticker_traded_at ON trade (ticker, traded_at);

-- 보유종목 (집계 결과, 전량 매도 시 row 삭제)
CREATE TABLE holding (
    ticker         VARCHAR(10)    PRIMARY KEY REFERENCES stock(ticker),
    quantity       NUMERIC(19, 4) NOT NULL,
    avg_buy_price  NUMERIC(19, 4) NOT NULL,
    updated_at     TIMESTAMP      NOT NULL DEFAULT now(),
    CONSTRAINT chk_holding_quantity      CHECK (quantity > 0),
    CONSTRAINT chk_holding_avg_buy_price CHECK (avg_buy_price >= 0)
);

-- 실현손익 (매도 1건당 1건, trade 와 1:1)
CREATE TABLE realized_profit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  BIGINT         NOT NULL UNIQUE REFERENCES trade(id),
    ticker          VARCHAR(10)    NOT NULL REFERENCES stock(ticker),
    sell_price      NUMERIC(19, 4) NOT NULL,
    avg_buy_price   NUMERIC(19, 4) NOT NULL,
    quantity        NUMERIC(19, 4) NOT NULL,
    profit          NUMERIC(19, 4) NOT NULL,
    realized_at     DATE           NOT NULL,
    created_at      TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX idx_realized_profit_realized_at ON realized_profit (realized_at);

-- 일간 포트폴리오 스냅샷 (snapshot_date UNIQUE 로 추이 인덱스 + 중복 방지 동시 해결)
CREATE TABLE portfolio_snapshot (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date            DATE           NOT NULL UNIQUE,
    total_asset              NUMERIC(19, 4) NOT NULL,
    total_evaluation_profit  NUMERIC(19, 4) NOT NULL,
    total_realized_profit    NUMERIC(19, 4) NOT NULL,
    total_return_rate        NUMERIC(10, 4) NOT NULL,
    created_at               TIMESTAMP      NOT NULL DEFAULT now()
);
